-- District Stocks Table
CREATE TABLE IF NOT EXISTS public.ilce_stoklari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id BIGINT REFERENCES public.depo_envanteri(id) ON DELETE CASCADE,
    ilce TEXT NOT NULL,
    stok_miktari DECIMAL(10,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(urun_id, ilce)
);

ALTER TABLE public.ilce_stoklari ENABLE ROW LEVEL SECURITY;
CREATE POLICY "District Stocks Public Access" ON public.ilce_stoklari FOR ALL USING (true);
