-- Copy and run this script in the Supabase SQL Editor

-- 1. Update Vehicles (Araclar) Table
ALTER TABLE public.araclar ADD COLUMN IF NOT EXISTS ilce TEXT;
ALTER TABLE public.araclar ADD COLUMN IF NOT EXISTS kilometre INTEGER DEFAULT 0;

-- 2. Update Tasks (Gorevler) Table
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS tarih_saat TIMESTAMPTZ;
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS arac_id BIGINT REFERENCES public.araclar(id);
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS cikis_km INTEGER;
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS donus_km INTEGER;
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS tur TEXT;
ALTER TABLE public.gorevler ADD COLUMN IF NOT EXISTS islem_turu TEXT;

-- 3. Create Task Personnel Junction Table (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.gorev_personel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gorev_id BIGINT REFERENCES public.gorevler(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Task Chemicals Table
CREATE TABLE IF NOT EXISTS public.gorev_ilaclar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gorev_id BIGINT REFERENCES public.gorevler(id) ON DELETE CASCADE,
    ilac_adi TEXT NOT NULL,
    miktar DECIMAL(10,2) NOT NULL,
    birim TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable RLS for new tables
ALTER TABLE public.gorev_personel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gorev_ilaclar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Gorev Personel Public Access" ON public.gorev_personel FOR ALL USING (true);
CREATE POLICY "Gorev Ilaclar Public Access" ON public.gorev_ilaclar FOR ALL USING (true);

-- 6. Add 'ilce' to Users if missing (assuming it might be missing in schema but present in app logic)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ilce TEXT;

-- 7. Update users table for Admin-Managed Auth
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT UNIQUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_id UUID;

-- 8. Clean up duplicate emails and enforce uniqueness (Smart Cleanup)
DO $$
DECLARE
    r RECORD;
    kept_id BIGINT;
    duplicate_id BIGINT;
    i INT;
BEGIN
    FOR r IN 
        SELECT email, ARRAY_AGG(id ORDER BY id DESC) as ids
        FROM public.users 
        WHERE email IS NOT NULL 
        GROUP BY email 
        HAVING COUNT(*) > 1
    LOOP
        -- The first ID is the one to keep (highest / latest ID)
        kept_id := r.ids[1];
        
        -- Loop through the duplicates (ids[2] and onwards)
        FOR i IN 2 .. ARRAY_LENGTH(r.ids, 1)
        LOOP
            duplicate_id := r.ids[i];
            
            -- Reassign references in 'task_crew' (if exists)
            -- We use a dynamic execute to avoid errors if table doesn't exist in some environments, though user has it.
            -- Also handling potential unique constraint violations by deleting if update would conflict
            BEGIN
                EXECUTE 'UPDATE public.task_crew SET user_id = $1 WHERE user_id = $2' USING kept_id, duplicate_id;
            EXCEPTION WHEN unique_violation THEN
                EXECUTE 'DELETE FROM public.task_crew WHERE user_id = $1' USING duplicate_id;
            WHEN undefined_table THEN
                -- Table might not exist, ignore
                NULL;
            END;

            -- Reassign references in 'gorev_personel'
            BEGIN
                UPDATE public.gorev_personel SET user_id = kept_id WHERE user_id = duplicate_id;
            EXCEPTION WHEN unique_violation THEN
                DELETE FROM public.gorev_personel WHERE user_id = duplicate_id;
            END;

            -- Reassign references in 'yoklama'
            BEGIN
                UPDATE public.yoklama SET user_id = kept_id WHERE user_id = duplicate_id;
            EXCEPTION WHEN unique_violation THEN
                DELETE FROM public.yoklama WHERE user_id = duplicate_id;
            END;

            -- Finally, delete the duplicate user
            DELETE FROM public.users WHERE id = duplicate_id;
        END LOOP;
    END LOOP;
END $$;

-- Then, add the UNIQUE constraint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_email_key') THEN
        ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
    END IF;
END $$;

-- 9. Add Entry/Exit Times to Attendance (Yoklama) Table
ALTER TABLE public.yoklama ADD COLUMN IF NOT EXISTS cikis_saati TIME DEFAULT '17:30';

-- 10. Inventory (Depo) Table
CREATE TABLE IF NOT EXISTS public.depo_envanteri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_adi TEXT NOT NULL,
    stok_miktari DECIMAL(10,2) NOT NULL DEFAULT 0,
    birim TEXT NOT NULL, -- Adet, Lt, Kg
    kritik_limit DECIMAL(10,2) NOT NULL DEFAULT 10,
    etkili_gun_sayisi INTEGER DEFAULT 0, -- Effective days
    aciklama TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.depo_envanteri ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Inventory Public Access" ON public.depo_envanteri FOR ALL USING (true);


-- 11. Stock History (Stok Hareketleri)
CREATE TABLE IF NOT EXISTS public.stok_hareketleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id BIGINT REFERENCES public.depo_envanteri(id) ON DELETE CASCADE,
    islem_turu TEXT NOT NULL, -- 'CIKIS', 'GIRIS'
    miktar DECIMAL(10,2) NOT NULL,
    ilce TEXT,
    teslim_alan_id BIGINT REFERENCES public.users(id),
    teslim_eden_id TEXT, 
    aciklama TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.stok_hareketleri ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Stock History Public Access" ON public.stok_hareketleri FOR ALL USING (true);

-- 12. Sources (Kaynaklar) Table
CREATE TABLE IF NOT EXISTS public.kaynaklar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baslik TEXT NOT NULL,
    tur TEXT, -- 'Dere Yatağı', 'Çöp Konteyneri', etc.
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    ilce TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.kaynaklar ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Sources Public Access" ON public.kaynaklar FOR ALL USING (true);

-- 13. Task Sources Junction Table
CREATE TABLE IF NOT EXISTS public.gorev_kaynaklar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gorev_id BIGINT REFERENCES public.gorevler(id) ON DELETE CASCADE,
    kaynak_id BIGINT REFERENCES public.kaynaklar(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.gorev_kaynaklar ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Task Sources Public Access" ON public.gorev_kaynaklar FOR ALL USING (true);
