-- Ensure Users Table exists
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_soyad TEXT NOT NULL,
    unvan TEXT,
    ilce TEXT,
    email TEXT UNIQUE,
    auth_id UUID UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    telefon TEXT,
    kan_grubu TEXT,
    durum TEXT DEFAULT 'aktif'
);

-- Permissions Table
CREATE TABLE IF NOT EXISTS public.permissions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT
);

-- User Permissions Junction Table
CREATE TABLE IF NOT EXISTS public.user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    permission_id TEXT REFERENCES public.permissions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, permission_id)
);

-- RLS
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid "already exists" errors
DROP POLICY IF EXISTS "Permissions Public Access" ON public.permissions;
DROP POLICY IF EXISTS "User Permissions Public Access" ON public.user_permissions;
DROP POLICY IF EXISTS "Users Public Access" ON public.users;

-- Create policies
CREATE POLICY "Permissions Public Access" ON public.permissions FOR SELECT USING (true);
CREATE POLICY "User Permissions Public Access" ON public.user_permissions FOR ALL USING (true);
CREATE POLICY "Users Public Access" ON public.users FOR ALL USING (true);

-- Initial Permissions Data
INSERT INTO public.permissions (id, name, category, description) VALUES
('inventory:view', 'Stok Görüntüleme', 'Stok', 'Depo envanterini görebilir'),
('inventory:manage', 'Stok Yönetimi', 'Stok', 'Ürün ekleyebilir, düzenleyebilir ve silebilir'),
('inventory:output', 'Ürün Çıkışı', 'Stok', 'Depodan ürün çıkışı yapabilir'),
('users:view', 'Kullanıcı Görüntüleme', 'Kullanıcı', 'Kullanıcı listesini görebilir'),
('users:manage', 'Kullanıcı Yönetimi', 'Kullanıcı', 'Yeni kullanıcı ekleyebilir, düzenleyebilir ve silebilir'),
('permissions:manage', 'Yetki Yönetimi', 'Sistem', 'Kullanıcı yetkilerini düzenleyebilir'),
('tasks:view', 'Görev Görüntüleme', 'Görev', 'Görev listesini ve detaylarını görebilir'),
('tasks:create', 'Yeni Görev', 'Görev', 'Yeni görev oluşturabilir'),
('tasks:manage', 'Görev Yönetimi', 'Görev', 'Görevleri düzenleyebilir ve silebilir'),
('vehicles:view', 'Araç Görüntüleme', 'Araç', 'Araç listesini görebilir'),
('vehicles:manage', 'Araç Yönetimi', 'Araç', 'Araç ekleyebilir, düzenleyebilir ve silebilir'),
('reports:view', 'Rapor Görüntüleme', 'Rapor', 'Sistem raporlarını görebilir'),
('attendance:view', 'Yoklama Görüntüleme', 'Yoklama', 'Yoklama listesini görebilir'),
('attendance:manage', 'Yoklama Yönetimi', 'Yoklama', 'Yoklama kaydı girebilir ve düzenleyebilir'),
('map:view', 'Harita Görüntüleme', 'Harita', 'Harita üzerindeki kaynakları ve ısı haritasını görebilir'),
('map:manage', 'Kaynak Yönetimi', 'Harita', 'Haritaya yeni kaynak ekleyebilir veya silebilir')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name, 
    category = EXCLUDED.category, 
    description = EXCLUDED.description;

-- Function to initialize default permissions for a user based on unvan
CREATE OR REPLACE FUNCTION public.initialize_user_permissions(target_user_id BIGINT, user_unvan TEXT)
RETURNS VOID AS $$
BEGIN
    -- Common permissions for everyone
    INSERT INTO public.user_permissions (user_id, permission_id)
    VALUES (target_user_id, 'inventory:view'), (target_user_id, 'tasks:view'), (target_user_id, 'vehicles:view'), (target_user_id, 'map:view'), (target_user_id, 'attendance:view')
    ON CONFLICT DO NOTHING;

    -- Role specific permissions
    IF user_unvan IN ('mudur', 'sef', 'bolge_sorumlusu') THEN
        INSERT INTO public.user_permissions (user_id, permission_id)
        SELECT target_user_id, id FROM public.permissions
        ON CONFLICT DO NOTHING;
    ELSIF user_unvan = 'ekipbasi' THEN
        INSERT INTO public.user_permissions (user_id, permission_id)
        VALUES 
            (target_user_id, 'inventory:output'),
            (target_user_id, 'tasks:create'),
            (target_user_id, 'tasks:manage'),
            (target_user_id, 'users:view'),
            (target_user_id, 'attendance:manage')
        ON CONFLICT DO NOTHING;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-initialize permissions when a user is created
CREATE OR REPLACE FUNCTION public.trigger_initialize_user_permissions()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM public.initialize_user_permissions(NEW.id, NEW.unvan);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_init_user_perms ON public.users;
CREATE TRIGGER tr_init_user_perms
AFTER INSERT ON public.users
FOR EACH ROW EXECUTE FUNCTION public.trigger_initialize_user_permissions();

-- Migration: Initialize permissions for existing users
DO $$
DECLARE
    r RECORD;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users') THEN
        FOR r IN SELECT id, unvan FROM public.users LOOP
            PERFORM public.initialize_user_permissions(r.id, r.unvan::text);
        END LOOP;
    END IF;
END $$;
